---
- name: Update apt
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - gnupg2
      - wget
      - python3-psycopg2
    state: latest

- name: Add PostgreSQL apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL Repo
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
    filename: postgresql
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name:
      - postgresql-{{ postgresql_version }}
      - libpq-dev
    state: latest
  notify: Enable Postgresql

- name: Enable PostgresSQL
  systemd:
    name: postgresql
    enabled: yes

- name: Start PostgresSQL
  systemd:
    name: postgresql
    state: started

- name: Ensure locales are present
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  notify: Restart Postgresql